name: Test unity-export-crunched-action

on:
  workflow_dispatch:

env:
  INPUT_PATH: input
  OUTPUT_PATH: output

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Output Directory
        run: |
          mkdir -p ${{ env.INPUT_PATH }}
          mkdir -p ${{ env.INPUT_PATH }}/sample
          mkdir -p ${{ env.OUTPUT_PATH }}

      - name: Download Test Image
        run: |
          curl -o ${{ env.INPUT_PATH }}/sample/001.png https://raw.githubusercontent.com/tp-jp/unity-export-crunched-action/refs/heads/main/Tests/Input/001.png

      - name: Export Crunched Textures
        uses: tp-jp/unity-export-crunched-action@v1
        with:
          input-path: ${{ env.INPUT_PATH }}
          output-path: ${{ env.OUTPUT_PATH }}
          unity-email: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-license: ${{ secrets.UNITY_LICENSE }}
          mipmap-enabled: false
          max-size: 2048
          resize-algorithm: 'Mitchell'
          compression-quality: 50

      - name: Check Output Files
        run: |
          # Check if output directory exists and contains subdirectories
          if [ ! -d "${{ env.OUTPUT_PATH }}" ]; then
            echo "Error: Output directory does not exist."
            exit 1
          fi

          # Count subdirectories
          subdir_count=$(find ${{ env.OUTPUT_PATH }} -mindepth 1 -type d | wc -l)
          if [ "$subdir_count" -eq 0 ]; then
            echo "Error: No subdirectories found in the output directory."
            exit 1
          fi
          echo "Output directory is valid. Contains $subdir_count subdirectories."

      - name: Upload exported bytes
        uses: actions/upload-artifact@v4
        with:
          name: crunched-textures
          path: ${{ env.OUTPUT_PATH }}
